spring:
  messages:
    basename: locale/ui/messages,locale/validation/messages
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:epictask
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8081
  security:
    user:
      name: admin
      password: admin

# actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

epictask:
  jwt:
    duration: 60000
    secret: zZpqvc2Y2nVIIjBMN%eKk&1ko*jj+IOw[Lo]EZP@Jvj5%RQz.wD;6aVh0)flvOsmX7mrRiQ5kTSCEY
