spring:
  messages:
    basename: locale/ui,locale/validation
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:epictask
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:8081

# actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
